### ISSUE TITLE
Create interface class file

### ISSUE THREAD

**Issue by thecruzmissile** [cs3398-borgs-bros/CS3398--Borgs-Bros--S2019#2]
This file will contain all the interfaces

**Comment by thecruzmissile** [comment]
- [x] Interface file needs to be part of the threesolid package.

- [x] Add IWorkable interface

- [x] AddIFeedable interface

 Interfaces given here: https://www.oodesign.com/interface-segregation-principle.html

**Comment by d-andres** [comment]
Review and approved by
- [x] @dal79 
- [ ] @thecruzmissile 
- [x] @waltergarciaguirre 
- [ ] @lukehelmcamp
